// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNSLbb75khJm9ne16Zg3eRkkNODYYFfbE',
    appId: '1:1079143255073:web:c9f18cadd5e55cfb51e760',
    messagingSenderId: '1079143255073',
    projectId: 'htg-smart-watch',
    authDomain: 'htg-smart-watch.firebaseapp.com',
    storageBucket: 'htg-smart-watch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yYOyyYXGVSkY5YI2UeASW7M4IK57MBo',
    appId: '1:1079143255073:android:205372c24ac934df51e760',
    messagingSenderId: '1079143255073',
    projectId: 'htg-smart-watch',
    storageBucket: 'htg-smart-watch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY28GNc4NHlChoFspDCpVYTqlHEp-fucM',
    appId: '1:1079143255073:ios:facc378e3505b35a51e760',
    messagingSenderId: '1079143255073',
    projectId: 'htg-smart-watch',
    storageBucket: 'htg-smart-watch.appspot.com',
    iosBundleId: 'com.example.htgSmartWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY28GNc4NHlChoFspDCpVYTqlHEp-fucM',
    appId: '1:1079143255073:ios:e3ce10379a89b35c51e760',
    messagingSenderId: '1079143255073',
    projectId: 'htg-smart-watch',
    storageBucket: 'htg-smart-watch.appspot.com',
    iosBundleId: 'com.example.htgSmartWatch.RunnerTests',
  );
}
